apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello-world-deploy
  labels:
    {{- include "edp-tekton.labels" . | nindent 4 }}
spec:
  params:
  - name: BASE_IMAGE
    type: string
    default: "alpine"
  - name: username
    type: string
  steps:
    - name: hello-world-deploy
      image: $(params.BASE_IMAGE)
      script: |
        #!/bin/sh
        echo "Hello $(params.username), the repository contains the following files:"
        ls -al
