apiVersion: v1
kind: ConfigMap
metadata:
  name: npm-settings
  labels:
    {{- include "edp-tekton.labels" . | nindent 4 }}
data:
  .npmrc-ci: |
    registry=${NEXUS_HOST_URL}/repository/edp-npm-group
    ${NEXUS_HOST}/repository/:email=ci.user@edp.com
    ${NEXUS_HOST}/repository/:_auth=${upBase64}
    cache=${NPM_CACHE_DIR}

  .npmrc-publish-snapshots: |
    registry=${NEXUS_HOST_URL}/repository/edp-npm-snapshots
    ${NEXUS_HOST}/repository/:email=ci.user@edp.com
    ${NEXUS_HOST}/repository/:_auth=${upBase64}
    cache=${NPM_CACHE_DIR}

  .npmrc-publish-releases: |
    registry=${NEXUS_HOST_URL}/repository/edp-npm-releases
    ${NEXUS_HOST}/repository/:email=ci.user@edp.com
    ${NEXUS_HOST}/repository/:_auth=${upBase64}
    cache=${NPM_CACHE_DIR}
